### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StinkerB06**
I edited the Platform table and marked the FCs that are currently available only under 64-bit environment.

### CODE REVIEW

**Comment by StinkerB06** [comment]
Click4 actually works under 32-bit Windows.

**Comment by StinkerB06** [comment]
Besides, I only see a 64-bit binary for Linux.

**Comment by josefnpat** [comment]
@StinkerB06 that does not mean it does not run on 32 bit linux.

**Comment by paladin-t** [comment]
Barely important information; doesn't make sense for browser, mobile, console based ones.

**Pull request closed without merging**
