### PR TITLE
Continuum 93

### PR DESCRIPTION
**Pull request by EnthusiastGuy**
Added Continuum 93. This is still work in progress, however, at this date, Continuum is fully working and anyone is able to write functional programs/games in its assembly language.

### CODE REVIEW

**Comment by paladin-t** [comment]
I got some trouble to launch, it holds me at the initial blank screen when I start "Continuum93.exe", and I can't get into the OS.

image

Here's its output:

[os.asm.output.zip](https://github.com/paladin-t/fantasy/files/11623471/os.asm.output.zip)

**Comment by EnthusiastGuy** [comment]
Hi there! Thanks for trying it out. The OS isn't much of a show-off for now, just a blinking cursor on the bottom left side of the screen. However, if you started the Tools and pressed F9, you most likely directly entered the step-by-step debugging mode and you'd easily confuse that with a freeze. Try running Continuum.exe without starting tools and type "run asm/kb-scan.asm", for example. I'd expect you to be able to load the keyboard scan then. After that, you could start up Tools and debug the execution if you'd want. Or write another assembly program with notepad and run it.
I'll try and clear this ambiguity in my documentation with the next release 
Again, I appreciate very much you taking a look, also thanks for this list! :D

**Comment by EnthusiastGuy** [comment]
Just did a few more tests here and all should be fine. Let me know what version of Windows are you running it onto or if it's a virtual machine. To be honest, I haven't tested on VM's.

**Comment by paladin-t** [comment]
Thanks for the information. I'm running a Win 10 (64bit), no VM, the language and locale is set to China.

I tried a clean launching without starting the tool, but the issue remained, it didn't respond to my input.

https://github.com/paladin-t/fantasy/assets/2062224/4b12b948-cb0e-43c9-bfbc-3ad100de3c89

**Comment by EnthusiastGuy** [comment]
Oh, I see what's going on! The video clarified it, thanks.
The good news is that it's working as intended. The bad news is that the user interface isn't the most clear.

So, what you're doing: you're starting to type on the virtual keyboard and you can see characters being fed to the emulator. Then you press Enter and the command is processed and immediately an error is shown on the top left of the same screen saying "Unknown command", because the command you entered is not recognized.
Screenshot

... but because you clicked on enter more than once, as soon as you hit enter a second time, the new empty command is processed and no error is shown.

The OS is currently a very basic one only allowing you a very limited set of actions.
You can try the command

cat

and that will show you a list of directories and files that reside in the "Data\filesystem" directory. Then, you can type:

run asm/kb-scan.asm

.. and that will load the demo program which is located in the "Data\filesystem\asm\kb-scan.asm" source file.

Anyway, point taken, for my next update I will improve the OS handling so messages are more visible and won't get cleared that fast. This version of the OS is a quick and dirty way for the user to be able to load *.asm files he can create to play with.

**Comment by paladin-t** [comment]
Ah, I was so impatient, thanks for the help.

Added to the list, look forward to see your future update.

**Comment by EnthusiastGuy** [comment]
No problem, I'll actually write a decent OS for next release 😊. Cheers and thanks!

**Pull request merged**
