### PR TITLE
Remove Zany80 from the list

### PR DESCRIPTION
**Pull request by pixelherodev**
I've abandoned Zany80, probably indefinitely; it's served its purpose as what was honestly more a research project than a console others could use.

### CODE REVIEW

**Comment by pixelherodev** [comment]
Thanks.

**Comment by PureAsbestos** [comment]
@farvardin it has been abandoned.

From the creator:
> I've abandoned Zany80, probably indefinitely; it's served its purpose as what was honestly more a research project than a console others could use.

**Comment by farvardin** [comment]
Ok. But it's a pity to remove it from the list, it might be taken over by someone else, it's open source

**Comment by pixelherodev** [comment]
I have actually started working on it a bit lately, but it's not currently usable. @farvardin If I get it back to the point of usability, I'll open a PR to readd it to the list; for now, there's no reason for it to be mentioned.

**Pull request merged**
