### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vircon32**
Added Vircon32 to the list of fantasy consoles

### CODE REVIEW

**Comment by vircon32** [comment]
Hi again paladin, it's been some time. As promised, I finally upgraded the sources for the emulator and dev tools. Now they build with CMake, and should be working under Linux and Mac too. This last one is yet untested, (I have no Mac users to test it right now). The repository for this is [here](https://github.com/vircon32/ComputerSoftware), in case you want to check it.

**Comment by paladin-t** [comment]
Good to see this progress! I might be missing something, but is there a link for users to download and play an out-of-box linux and mac version?

**Comment by vircon32** [comment]
Not yet. I may be able to build and upload linux binaries shortly, but for the Mac one it seems I will need help from someone with a real Mac machine. I have located someone but it may take some time. It is ok if we postpone updating your list until this is done.

**Comment by vircon32** [comment]
> It is ok if we postpone updating your list until this is done.

Well, building the Mac version took way longer than expected, but it is done.
The binaries for all platforms are now available in the corresponding releases here:
Emulator: https://github.com/vircon32/ComputerSoftware/releases/tag/emulator-v22.6.4
Dev Tools: https://github.com/vircon32/ComputerSoftware/releases/tag/devtools-v22.6.4

**Comment by paladin-t** [comment]
Updated. Congrats!

**Comment by vircon32** [comment]
Thank you! :)

**Pull request merged**
