### PR TITLE
Added raccoon

### PR DESCRIPTION
**Pull request by Lyatus**
I didn't know if I should put Unlicense or Public Domain in the License section, feel free to change it. Also I was surprised there wasn't any public domain fantasy consoles already, what's up with that?

Thanks for maintaining this list!

### CODE REVIEW

**Comment by PureAsbestos** [comment]
You really ought to license it as [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) as some countries don't allow you to simply place your work into the public domain.

**Comment by Lyatus** [comment]
I'm already licensing it as Unlicense, would there really be any benefits switching to CC0?

**Comment by PureAsbestos** [comment]
Unlicense occupies a gray area, and may be illegal/non-binding in some jurisdictions. CC0, is more comprehensive, and ensures that your software is as free as possible in jurisdictions that, say, have no concept of public domain.

**Comment by paladin-t** [comment]
Thanks for adding it!

Would you prefer to switch it to CC0 or other license before merging or leave it as is?

**Comment by Lyatus** [comment]
Leave it as it is for now, I'm grateful for the license suggestion but I'll have to reflect on that before making the change :)

I'll be sure to do another pull request if any info changes, if that's alright with you.

**Comment by paladin-t** [comment]
Anytime you wish.

**Pull request merged**
