### PR TITLE
Added a status/version column

### PR DESCRIPTION
**Pull request by capturts**

### CODE REVIEW

**Comment by capturts** [comment]
I really hope I've done this right, I've added an extra column for a latest version and latest activity. I've tried to add the current details as well as I can.

**Comment by paladin-t** [comment]
A version number or updated date doesn't say much relevant information, since they are released from different start number. Some from v0.1, the other from v1.0, and increase apart.

**Comment by capturts** [comment]
I see that version might not be the most useful (although you might spot if it's time to update or not), maybe a "last activity" and/or "last release" and/or "active"/"abandoned" or something like that?

**Comment by Torbuntu** [comment]
Who will keep that column updated?

**Comment by capturts** [comment]
If we could agree about what things would be relevant, I'd be happy to check at least monthly.

**Pull request closed without merging**
