### PR TITLE
TIC-80 is available for 3DS

### PR DESCRIPTION
**Pull request by stevenfelix505**
Someone named [@borbware](https://t.me/borbware) in [TIC-80 Community](https://t.me/TIC80) shared some videos about TIC-80 running on 3DS.
You can get it from [TIC-80 GitHub Actions](https://github.com/nesbox/TIC-80/actions)

### CODE REVIEW

**Review by stevenfelix505 — COMMENTED** [review]
Someone named [@borbware](https://t.me/borbware) in [TIC-80 Community](https://t.me/TIC80) shared some videos about TIC-80 running on 3DS.
You can get it from [TIC-80 GitHub Actions](https://github.com/nesbox/TIC-80/actions)

**Comment by paladin-t** [comment]
Is there a ready to use link to download the brew 3ds/cia file?

**Comment by stevenfelix505** [comment]
Yes

**Comment by paladin-t** [comment]
Didn't find. And where can I download it?

**Comment by stevenfelix505** [comment]
Just click [TIC-80 GitHub Actions](https://github.com/nesbox/TIC-80/actions) then click on workflows like "C Implementation of Wu's Color Quantizer", then scroll up until you find a artifact named "tic80-nintendo-3ds" click it to download.

**Comment by paladin-t** [comment]
Sorry I must miss something, or it's just the build log for me.

图片

**Comment by paladin-t** [comment]
Ok, I found it, I was blind.

**Comment by paladin-t** [comment]
Tested on my 3DS. Thanks for the info and explanation.

**Pull request merged**
