### PR TITLE
Add TEC Redshift fantasy console

### PR DESCRIPTION
**Pull request by red-hara**
TEC Redshift is console in EXAPUNKS world made by Zachtronics with red-blue 3D.

### CODE REVIEW

**Comment by paladin-t** [comment]
Looks fascinating. If I'm understanding this correct, Tec Redshift is the program player of EXAPUNKS. Although it's not explicitly pointed out, we often have an agreement that a FC should offer built-in editors, or at the very least be possible to use generic external editors (notepad etc.) to write programs using the full functionalities. I found TEC programs are distributed in an exclusive picture format, that makes it impossible to make a program without owning EXAPUNKS.

I haven't tried the EXAPUNKS yet, but I just wonder, is it the only requirement for both writing and playing the programs? If so, would you mind modifying it by linking to the main program instead of the player?

**Comment by red-hara** [comment]
My bad, you are right.
Truly, Redshift is ONLY player, not full editor.
To obtain Redshift in main game one has to complete list of story quests.
Shall I point to original EXAPUNKS game or should I just abort this pull request?

**Comment by paladin-t** [comment]
I see. I consider it a game (maybe name it meta-game or something) with conventional TODO-list, competitions, etc. I'd be glad to merge it if it allowed playing and creating right out of box.

I think it still worth a try, because everything looks very good. Thanks anyway!

**Comment by red-hara** [comment]
Updated Redshift description in c7a81211f941ecfa131743985da83c2facbcad3c.

**Comment by paladin-t** [comment]
Sorry I didn't make it clear, English is not my native.

It's a great game, but I prefer not to merge it, if the `story mode quests` must be accomplished before one can write programs freely using all APIs, and share with others. Shall I close this if I'm not missing anything?

**Comment by red-hara** [comment]
Yep, closing then.

**Pull request closed without merging**
